workflows:
  android-release:
    name: EMFAD Android Release Build
    max_build_duration: 180
    instance_type: mac_mini_m2

    script:
      - checkout
      - run:
          name: Java-Version prüfen
          command: |
            echo "Java-Version prüfen"
            java -version
            javac -version
      - run:
          name: Gradle-Build ausführen
          command: |
            ./gradlew assembleRelease \
              -Pandroid.enableJetifier=true \
              -Pandroid.useAndroidX=true

    artifacts:
      - app/build/outputs/apk/release/*.apk
      - app/build/reports/
