workflows:
  android-release:
    name: EMFAD Android Release Build
    max_build_duration: 180
    instance_type: mac_mini_m2

    environment:
      vars:
        JAVA_HOME: /Library/Java/JavaVirtualMachines/zulu-11.jdk/Contents/Home

    scripts:
      - name: Java-Version prüfen
        script: |
          echo "Java-Version prüfen"
          java -version
          javac -version

      - name: Gradle-Build ausführen
        script: |
          ./gradlew assembleRelease \
            -Pandroid.enableJetifier=true \
            -Pandroid.useAndroidX=true

    artifacts:
      - app/build/outputs/apk/release/*.apk
      - app/build/reports/
