workflows:
  android-release:
    name: EMFAD Android Release Build
    max_build_duration: 180
    instance_type: mac_mini_m2
    
    # Entfernt: flutter_sdk (da dies eine native Android-App ist)

    script:
      - checkout
      - echo "Java-Version prüfen"
      - java -version
      - javac -version
      - ./gradlew assembleRelease -Pandroid.enableJetifier=true -Pandroid.useAndroidX=true

    artifacts:
      - app/build/outputs/apk/release/*.apk
      - app/build/reports/
